language: ruby

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8969
  - gem update --system

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0 # workaround https://github.com/travis-ci/travis-ci/issues/7848
  - 2.5

os:
  - osx
  - linux

matrix:
  # http://rubies.travis-ci.org/
  exclude:
  - os: osx
    rvm: 1.9
  - os: osx
    rvm: 2.0
